# Generated by Django 5.0.6 on 2024-06-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='engine_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='fuel_consumption',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='number_of_hp',
            field=models.IntegerField(default=0.0),
        ),
    ]
